[features]
seeds = false
skip-lint = false
[programs.localnet]
soltrek_program = "GESymwz7zdZ7uu7QYkpxNEtgEmDhZUQntgMYbZueD5te"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/bolt/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
